name: Generate Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write  # مهم

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate sitemap.xml
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
        echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
        find . -name "*.html" | grep -v "404.html" | while read file; do
          clean_path=${file#./}
          url="https://v2help.github.io/${clean_path}"
          echo "  <url><loc>${url}</loc><changefreq>monthly</changefreq></url>" >> sitemap.xml
        done
        echo '</urlset>' >> sitemap.xml

    - name: Commit and push sitemap
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add sitemap.xml
        git commit -m "Auto-generate sitemap.xml" || echo "No changes to commit"
        git push
